sudo: required
language: java
before_script:
- wget http://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
- mkdir /home/travis/test/
- unzip chromedriver_linux64.zip -d /home/travis/test/
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script: mvn clean test -P main-suite

