sudo: required
language: java
dist: trusty
addons:
  chrome: stable # have Travis install Chrome stable.
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn test


script: mvn clean test -P main-suite

